# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2d4c53792106a3fbf0ef78e631551dd9426a4a77731391985afcb0d03665d43b094d40fc23573142f782bba133d2554c7f53f97af3cab5151f2ec76dec83255

test:
  secret_key_base: b14c64d065d8e03de7df2bec18dd96bb406524d62b7aa283b41f21d2dd63e7f4af5fc2417ca5e0286afe2a631b9e04c732c5db6e75f110c628860bee1ef1b193

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
